### ISSUE TITLE
Use composer for autoloading

### ISSUE THREAD

**Issue by grimicorn** [sincspecv/rsvp#5]
If you set up autoloading you do not have to individually require/include each class. For the current name space `TheFancyRobot\RSVP` If you add the below configuration to your composer.json you can put all of the classes in a `lib/RSVP` directory.

**Add in compser.json**

```
  "autoload": {
        "psr-4": {"TheFancyRobot\\": "lib/"}
    }
```

**Add somewhere that would be loaded on every request such as a shared header.php**
`require __DIR__ . '/vendor/autoload.php';`

[Composer Autoloading Documentation](https://getcomposer.org/doc/01-basic-usage.md#autoloading)

**Comment by sincspecv** [comment]
This requires me to include the config.php in classes.php. Is there a way around this?

**Comment by grimicorn** [comment]
I would probably lean towards having a file such as bootstrap.php that you can use to "Bootstrap" the application in there you can include the auto loading file autoload.php referenced in the original comment, config.php along with anything else you need to include. You can then include this file into a shared header.php or into each individual PHP file if you do not want to go the shared header.php route.

Regardless if you use auto loading or not a bootstrap.php file would be a good addition since it would allow you to include everything in one place wether it be a file like configure.php or a class
