### ISSUE TITLE
Finalize basic SMS functionality/Live server

### ISSUE THREAD

**Issue by grimicorn** [sincspecv/rsvp#8]
The best way to handle his one may be to put it onto a live server so a tunnel will not have to be created to test the basic functionality.
Since the project is on Github you can use [deploybot.com](deploybot.com) to handle the deployments once changes are made locally. It is easy to setup works directly with Github and you can deploy when code is pushed to the master branch

**Comment by sincspecv** [comment]
SMS is working, and I am working on getting it on a live server right now. However, the issue with it being on a live server is that there will be no error reporting. The only way to see the errors is to look at the apache log files. Ngrok displays the errors on every request, which makes it a lot easier to troubleshoot.

**Comment by sincspecv** [comment]
I have the site hosted on AWS and everything works aside from the sms functionality. The logs are showing this: 

```
54.177.88.146 (-) - - [07/Jun/2016:19:18:58 +0000] "POST /sms.php HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.35 Safari/535.1"
54.219.112.127 (-) - - [07/Jun/2016:19:28:15 +0000] "POST /sms.php HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.35 Safari/535.1"
54.177.70.197 (-) - - [07/Jun/2016:19:30:16 +0000] "POST /sms.php HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.35 Safari/535.1"
```

It doesn't look to be throwing any errors, but it's not updating the database or responding to the sms. Oddly, when I query the database in MySQL Workbench it doesn't look like the new user I created is in the database either. I can login in/out just fine with the new user.

**Comment by grimicorn** [comment]
If you want to email me the connection details for the server/database I can take a look. This is something we can hold on as long as you are not experiencing the bugs we spoke about in our meeting anymore.
